namespace Mre.OTI.Presupuesto.Application.Util
{
    public class Constantes
    {
        public struct SISTEMA
        {
   
            public const string KEY_ENCRYPT = "COLOCARFRASEENCRIPTACIONPARAPROYECTO"; /*FRASE PARA ENCRIPTACOIPM DE APP*/
            public const string KEY_ENCRYPT_LOGIN = "KEY_ENCRYPT_LOGIN_BASE_DATOS"; /*FRASE PARA ENCRIPTACION DE BD*/
            public const string VAR_AUDITORIA_HEADER = "X-Auditoria";
            public const string VAR_AUTORIZATION_HEADER = "Authorization";
            public const string VAR_VAL_ZERO_ENCRYPT = "0";
            public const string VAR_ACTION_RECAPTCHA_CI = "_queryci";
            public const string VAR_ACTION_RECAPTCHA_EXT = "_loginext";
            public const string VAR_ACTION_RECAPTCHA_PRI = "_loginback";
        }
       
        public struct GenericValues
        {
            public const string InternalError = "HUBO UN PROBLEMA AL PROCESAR LA SOLICITUD, INTENTE NUEVAMENTE POR FAVOR.";
        }
        public struct MensajesError
        {        
            public const string PAGINA_ACTUAL_VALIDAR = "PÁGINA ACTUAL NO PUEDE SER MENOR A CERO.";
            public const string TAMAÑO_PAGINA_VALIDAR = "TAMAÑO DE PÁGINA ACTUAL NO PUEDE SER MENOR A CERO.";
            public const string EX_UNPROCESSABLE_ENTITY = "NO INGRESÓ TODOS LOS PARÁMETROS OBLIGATORIOS.";
            public const string EX04_M01 = "DEBE INGRESAR POR LO MENOS UN CRITERIO DE BÚSQUEDA.";
                        
            /*MRE INCIO*/

            public const string EX_CATALOGO_ITEM_NOTFOUND = "NO SE ENCONTRÓ EL ID DE LA BOLSA DE HORAS BASE.";
            public const string EX_CATALOGO_ITEM_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR CATALOGO ITEM. LA DESCRIPCION DEL CATALOGO ITEM ES REQUERIDO";
            public const string EX_CATALOGO_ITEM_ERROR_INSERT = "YA EXISTE BOLSA DE HORAS PARA LA INSTITUCIÓN EDUCATIVA SELECCIONADA. NO SE PUEDE REGISTRAR LA BOLSA DE";
            public const string EX_CATALOGO_ITEM_CATALOGO_REQUIRED = "NO SE PUEDE REGISTRAR ITEM DEL CATALOGO. EL CATALOGO ES REQUERIDO";
            public const string EX_CATALOGO_ITEM_NOMBRE_DP = "NO SE PUEDE GRABAR ITEM DEL CATALOGO. LA DESCRIPCION DEL ITEM DEL CATALOGO YA EXISTE";
            public const string EX_CATALOGO_ITEM_CODIGO_DP = "NO SE PUEDE GRABAR ITEM DEL CATALOGO. EL CODIGO DEL ITEM DEL CATALOGO YA EXISTE";
            public const string EX_CATALOGO_ITEM_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR ITEM DE CATALOGO. ID DE ITEM DE CATALOGO ES REQUERIDO";


            public const string EX_CATALOGO_NOMBRE_REQUIRED = "NO SE PUEDE REGISTRAR   CATALOGO. LA DESCRIPCION DEL CATALOGO ES REQUERIDO";
            public const string EX_CATALOGO_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR CATALOGO. ID DE CATALOGO ES REQUERIDO";
            public const string EX_CATALOGO_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR CATALOGO. ID DE CATALOGO ES REQUERIDO";

            public const string EX_CATALOGO_DESCRIPCION_DP = "NO SE PUEDE GRABAR CATALOGO. NOMBRE DE CATALOGO YA EXISTE.";
            public const string EX_CATALOGO_CODIGO_DP = "NO SE PUEDE GRABAR CATALOGO. CODIGO DE CATALOGO YA EXISTE.";

            public const string EX_ERROR_GENERICO = "HUBO UN PROBLEMA AL PROCESAR LA SOLICITUD, INTENTE NUEVAMENTE POR FAVOR.";

            public const string EX_USUARIO_UPDATE_ERROR = "PERSONAL NO SE PUDO ACTUALIZAR. COMUNIQUESE CON EL ADMINISTRADOR";
            public const string EX_USUARIO_INSERT_ERROR = "PERSONAL NO SE PUDO REGISTRAR. COMUNIQUESE CON EL ADMINISTRADOR.";
            public const string EX_USUARIO_NOMBRE_REQUIRED = "NO SE PUEDE REGISTRAR PERSONAL. EL NOMBRE DEL PERSONAL ES REQUERIDO";
            public const string EX_USUARIO_TIPO_DOCUMENTO_REQUIRED = "NO SE PUEDE REGISTRAR PERSONAL. EL TIPO DE DOCUMENTO DEL PERSONAL ES REQUERIDO";
            public const string EX_USUARIO_USUARIO_NT_REQUIRED = "NO SE PUEDE REGISTRAR PERSONAL. EL PERSONAL DE ACCESO PARA BACKOFFICE ES REQUERIDO";
            public const string EX_USUARIO_CLAVE_NT_REQUIRED = "NO SE PUEDE REGISTRAR PERSONAL. LA CLAVE DE ACCESO PARA BACKOFFICE ES REQUERIDO";
            public const string EX_USUARIO_ID_PERSONA_REQUIRED = "NO SE PUEDE REGISTRAR PERSONAL. EL ID DE PERSONA ES REQUERIDO";

            public const string EX_USUARIO_CORREO_DP = "NO SE PUEDE GRABAR PERSONAL. EL CORREO DEL PERSONAL YA EXISTE.";
            public const string EX_USUARIO_NUMERO_DOCUMENTO_DP = "NO SE PUEDE GRABAR PERSONAL. EL NUMERO DE DOCUMENTO DEL PERSONAL YA EXISTE.";
            public const string EX_USUARIO_NT_DP = "NO SE PUEDE GRABAR PERSONAL. EL NOMBRE DE PERSONAL NT INGRESADO YA EXISTE.";
            public const string EX_USUARIO_NUMERO_DOCUMENTO_REQUIRED = "NO SE PUEDE GRABAR PERSONAL. EL NUMERO DE DOCUMENTO DEL PERSONAL ES REQUERIDO.";
            public const string EX_USUARIO_APELLIDO_PATERNO_REQUIRED = "NO SE PUEDE GRABAR PERSONAL. EL APELLIDO PATERNO DEL PERSONAL ES REQUERIDO.";

            public const string EX_USUARIO_ELIMINAR_ACCESO_ACTIVO = "EL PERSONAL SE ENCUENTRA CON UN ROL ASIGNADO. NO SE PUEDE ELIMINAR PERSONAL.";

            public const string EX_USUARIO_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR PERSONAL. ID DE PERSONAL ES REQUERIDO";
            public const string EX_USUARIO_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR PERSONAL. ID DE PERSONAL ES REQUERIDO";

            public const string EX_ROL_NOMBRE_REQUIRED = "NO SE PUEDE REGISTRAR ROL. EL NOMBRE DEL ROL ES REQUERIDO";
            public const string EX_ROL_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR ROL. ID DE ROL ES REQUERIDO";
            public const string EX_ROL_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR ROL. ID DE ROL ES REQUERIDO";
            public const string EX_ROL_NOMBRE_DP = "NO SE PUEDE GRABAR ROL. NOMBRE DE ROL YA EXISTE.";


            public const string EX_USUARIOROL_UPDATE_IDROL_REQUIRED = "NO SE PUEDE ACTUALIZAR ACCESO. INGRESE ID ROL.";
            public const string EX_USUARIOROL_UPDATE_IDUSUARIOROL_REQUIRED = "NO SE PUEDE ACTUALIZAR ACCESO. INGRESE ID PERSONAL ROL.";

            public const string EX_USUARIOROL_INSERT_IDROL_REQUIRED = "NO SE PUEDE REGISTRAR ACCESO. INGRESE ID ROL.";
            public const string EX_USUARIOROL_INSERT_IDUSUARIO_REQUIRED = "NO SE PUEDE REGISTRAR ACCESO. INGRESE ID PERSONAL.";

            public const string EX_USUARIOROL_DELETE_IDROL_REQUIRED = "NO SE PUEDE ELIMINAR ACCESO. INGRESE ID ROL.";

            public const string EX_USUARIOROL_DELETE_NOOK = "INFORME NO PUDO SER ELIMINADO.";
            public const string EX_USUARIOROL_UPDATE_NOOK = "INFORME NO PUDO SER ACTUALIZADO.";
            public const string EX_USUARIOROL_INSERT_NOOK = "INFORME NO PUDO REGISTRARSE.";

            public const string EX_USUARIOROL_USUARIO_ROL_DP = "NO SE PUEDE GRABAR ACCESO. PERSONAL YA TIENE ACCESO CON ESTE ROL.";
            public const string EX_USUARIOROL_GRUPO_REQUIRED = "NO SE PUEDE GRABAR ACCESO. EL ROL DE ANALISTA REQUIERE DE LA SELECCION DE UN GRUPO DE ATENCION DE PAISES.";
            public const string EX_USUARIOROL_CentroCosto_REQUIRED = "NO SE PUEDE GRABAR ACCESO. EL ROL DE CentroCosto REQUIERE DE LA SELECCION DE UNA CentroCosto.";

            public const string EX_LOGIN_USERNT_REQUIRED = "DEBE INGRESAR EL PERSONAL NT";
            public const string EX_LOGIN_PWD_REQUIRED = "DEBE INGRESAR SU CONTRASEÑA";
            public const string EX_LOGIN_USERNT_NOT_FOUND = "PERSONAL Y CONTRASEÑA DE WINDOWS NO SON VÁLIDOS.";
            public const string EX_LOGIN_USERNT_NOT_FOUND_AD = "PERSONAL Y CONTRASEÑA DE WINDOWS NO SE ENCONTRARON EN EL DIRECTORIO ACTIVO.";

            public const string EX_LOGIN_USERBD_NOT_FOUND = "PERSONAL QUE INTENTA ACCEDER AL SISTEMA NO TIENE PERMISOS. COMUNÍQUESE CON EL ADMINISTRADOR.";
            public const string EX_LOGIN_EXT_USERBD_NOT_FOUND = "LAS CREDENCIALES CON EL QUE INTENTA ACCEDER AL SISTEMA NO TIENE PERMISOS. COMUNÍQUESE CON EL ADMINISTRADOR.";

            public const string EX_CLASIFICACIONPERSONAL_NOMBRE_REQUIRED = "NO SE PUEDE REGISTRAR. CAMPO NOMBRE ES REQUERIDO. ";
            public const string EX_CLASIFICACIONPERSONAL_NOMBRE_DP = "NO SE PUEDE REGISTRAR. YA EXISTE UN CAMPO CON ESE NOMBRE. ";
            public const string EX_CLASIFICACIONPERSONAL_SIGLA_DP = "NO SE PUEDE REGISTRAR. YA EXISTE UN CAMPO CON ESA SIGLA. ";

            public const string EX_CLASIFICACIONPERSONAL_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR. SE REQUIERE EL ID";
            public const string EX_CLASIFICACIONPERSONAL_ACTUALIZAR_NOMBRE_REQUIRED = "NO SE PUEDE ACTUALIZAR. SE REQUIERE UNA DENOMINACION";
            public const string EX_CLASIFICACIONPERSONAL_ACTUALIZAR_SIGLA_REQUIRED = "NO SE PUEDE ACTUALIZAR. SE REQUIERE UNA SIGLA";

            public const string EX_CLASIFICACIONPERSONAL_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR. SE REQUIERE EL ID";


            public const string EX_PROYECTOMCC_NOMBRE_REQUIRED = "NO SE PUEDE REGISTRAR PROYECTO MCC. EL NOMBRE DEL PROYECTO ES REQUERIDO";
            public const string EX_PROYECTOMCC_NOMBRE_DP = "NO SE PUEDE GRABAR EL PROYECTO. EL NOMBRE YA EXISTE";
            public const string EX_PROYECTOMCC_ID_REQUIRED = "DEBE INGRESAR EL ID DEL PROYECTO";
            public const string EX_PROYECTOMCC_IDTIPODOCUMENTO_REQUIRED = "DEBE INGRESAR EL ID DEL DOCUMENTO DEL PROYECTO";
            public const string EX_PROYECTOMCC_IDESTADO_REQUIRED = "DEBE INGRESAR EL ID ESTADO DEL PROYECTO";
            public const string EX_PROYECTOMCC_NUMERODOCUMENTO_REQUIRED = "DEBE INGRESAR EL NUMERO DE DOCUMENTO";
            public const string EX_PROYECTOMCC_NOMBREPROYECTO_REQUIRED = "DEBE INGRESAR EL NOMBRE DEL PROYECTO";
            public const string EX_PROYECTOMCC_MES_REQUIRED = "DEBE INGRESAR EL MES";
            public const string EX_PROYECTOMCC_ANIO_REQUIRED = "DEBE INGRESAR EL AÑO";
            public const string EX_PROYECTOMCC_CANTIDADCARGOS_REQUIRED = "DEBE INGRESAR LA CANTIDAD DE CARGOS";
            public const string EX_PROYECTOMCC_DOCUMENTORUTA_REQUIRED = "DEBE INGRESAR EL DOCUMENTO RUTA";

            public const string EX_PROYECTOMCC_DOCUMENTO_DP = "EL DOCUMENTO YA EXISTE";

            public const string EX_CARGO_ESTRUCTURAL_DETALLE_ID_REQUIRED = "DEBE INGRESAR EL ID DE CARGO ESTRUCTURAL DETALLE";
            public const string EX_CARGO_ESTRUCTURAL_DETALLE_NOT_FOUND = "NO SE ENCONTRÓ EL REGISTRO, INGRESE UN CARGO ESTRUCTURAL DETALLE CORRECTO";

            public const string EX_PROYECTO_CARGO_REQUISITO_ID_REQUIRED = "DEBE INGRESAR EL ID DE PROYECTO CARGO REQUISITO";
            public const string EX_PROYECTO_CARGO_REQUISITO_DESCRIPCION_REQUIRED = "DEBE INGRESAR LA DESCRIPCION DE PROYECTO CARGO REQUISITO";

            public const string EX_PROYECTO_CARGO_FUNCION_ID_REQUIRED = "DEBE INGRESAR EL ID DE PROYECTO CARGO FUNCION";
            public const string EX_PROYECTO_CARGO_FUNCION_DESCRIPCION_REQUIRED = "DEBE INGRESAR LA DESCRIPCION DE PROYECTO CARGO FUNCION";

            public const string EX_PROYECTOEO_NOMBRE_REQUIRED = "DEBE INGRESAR EL NOMBRE DEL PROYECTO ESTRUCTURA ORGANIZACIONAL";
            public const string EX_PROYECTOEO_NOMBRE_DP = "NO SE PUEDE REGISTRAR PROYECTO EO. EL NOMBRE DEL PROYECTO ES REQUERIDO";
            public const string EX_PROYECTOEO_ID_REQUIRED = "DEBE INGRESAR EL ID DEL PROYECTO ESTRUCTURA ORGANIZACIONAL.";
            public const string EX_PROYECTOEO_MES_REQUIRED = "DEBE INGERSAR EL MES DEL PROYECTO ESTRUCTURA ORGANIZACIONAL";
            public const string EX_PROYECTOEO_ANIO_REQUIRED = "DEBE INGRESAR EL ANIO DEL PROYECTO ESTRUCTURA ORGANIZACIONAL";

            public const string EX_PROYECTOEODETALLE_NATURALEZA_ID_REQUIRED = "DEBE INGRESAR LA NATURALEZA DEL ELEMENTO.";
            public const string EX_PROYECTOEODETALLE_TIPO_ID_REQUIRED = "DEBE INGRESAR EL TIPO DEL ELEMENTO.";
            public const string EX_PROYECTOEODETALLE_DENOMINACION_ID_REQUIRED = "DEBE INGRESAR LA DENOMINACION DEL ELEMENTO.";

            #region PERSONA
            public const string EX_PERSONA_INSERT_NOOK = "LA PERSONA INGRESADA NO SE PUDO REGISTRAR";
            public const string EX_PERSONA_UPDATE_NOOK = "LA PERSONA SELECCIONADA NO PUDO SER ACTUALIZADA.";
            public const string EX_PERSONA_DELETE_NOOK = "LA PERSONA SELECCIONADA NO PUDO SER ELIMINADA";
            public const string EX_PERSONA_ID_REQUIRED = "DEBE INGRESAR ID DE LA PERSONA";
            public const string EX_PERSONA_NOT_FOUND = "NO SE PUDO ENCONTRAR A LA PERSONA SELECCIONADA.";
            public const string EX_PERSONA_USUARIO_ACTIVO = "LA PERSONA SELECCIONADA TIENE ASIGNADO UN PERSONAL EN EL SISTEMA. NO SE PUDO ELIMINAR A LA PERSONA.";

            public const string EX_PERSONA_NOMBRE_REQUIRED = "DEBE INGRESAR NOMBRE DE LA PERSONA";
            public const string EX_PERSONA_APELLIDO_PATERNO_REQUIRED = "DEBE INGRESAR APELLIDO PATERNO DE LA PERSONA";
            public const string EX_PERSONA_APELLIDO_MATERNO_REQUIRED = "DEBE INGRESAR APELLIDO MATERNO DE LA PERSONA";
            public const string EX_PERSONA_DOCUMENTO_REQUIRED = "DEBE INGRESAR NUMERO DE DOCUMENTO DE LA PERSONA";
            public const string EX_PERSONA_TIPO_DOCUMENTO_REQUIRED = "DEBE INGRESAR TIPO DE DOCUMENTO DE LA PERSONA";

            public const string EX_PERSONA_ESTADO_CIVIL_REQUIRED = "DEBE INGRESAR ESTADO CIVIL DE LA PERSONA";
            public const string EX_PERSONA_FECHA_NACIMIENTO_REQUIRED = "DEBE INGRESAR LA FECHA DE NACIMIENTO DE LA PERSONA";
            public const string EX_PERSONA_SEXO_REQUIRED = "DEBE INGRESAR EL SEXO DE LA PERSONA";
            public const string EX_PERSONA_PAIS_NACIMIENTO_REQUIRED = "DEBE INGRESAR PAIS DE NACIMIENTO DE LA PERSONA";
            public const string EX_VALIDATE_CORREO_GENERAL = "DEBE INGRESAR UNA DIRECCION DE CORREO VALIDO";
            public const string EX_PERSONA_TELEFONO_REQUIRED = "DEBE INGRESAR EL TELEFONO DE LA PERSONA";

            public const string EX_PERSONA_DOCUMENTO_DP = "EL NUMERO DE DOCUMENTO Y TIPO DE DOCUMENTO YA SE ENCUENTRAN REGISTRADOS";

            public const string EX_ESPECIFICA_CLASIFICADOR_DP = "NO SE PUEDE GRABAR EL CLASIFICADOR. CLASIFICADOR YA EXISTE.";
            public const string EX_ESPECIFICA_ID_CLASIFICADOR_DP = "NO SE PUEDE GRABAR ID CLASIFICADOR. ID CALSIFICADOR YA EXISTE.";

            public const string EX_CCOSTOS_CODIGO_COSTOS = "NO SE PUEDE GRABAR EL CODIGO COSTOS. YA EXISTE.";
            public const string EX_CCOSTOS_ID_CENTRO_COSTOS = "NO SE PUEDE GRABAR ID COSTOS. ID COTOS YA EXISTE.";

            public const string EX_POLITICAS_CODIGO_POLITICAS = "NO SE PUEDE GRABAR EL CODIGO POLITICAS. YA EXISTE.";
            public const string EX_POLITICAS_ID_POLITICAS = "NO SE PUEDE GRABAR ID POLITICAS. ID YA EXISTE.";

            public const string EX_OBJETIVOS_CODIGO_OBJETIVOS = "NO SE PUEDE GRABAR EL CODIGO OBJETIVOS. YA EXISTE.";
            public const string EX_OBJETIVOS_ID_OBJETIVOS = "NO SE PUEDE GRABAR ID OBJETIVOS. ID YA EXISTE.";

            public const string EX_ACCIONES_CODIGO_OBJETIVOS = "NO SE PUEDE GRABAR EL CODIGO ACCIONES. YA EXISTE.";
            public const string EX_ACCIONES_ID_OBJETIVOS = "NO SE PUEDE GRABAR ID ACCIONES. ID YA EXISTE.";

            public const string EX_OBJETIVOS_INSTITUCIONALES_CODIGO_OBJETIVOS = "NO SE PUEDE GRABAR EL CODIGO OBJETIVOS. YA EXISTE.";
            public const string EX_OBJETIVOS_INSTITUCIONALES_ID_OBJETIVOS = "NO SE PUEDE GRABAR ID OBJETIVOS. ID YA EXISTE.";

            public const string EX_OBJETIVOS_INSTITUCIONALES_CODIGO_ACCIONES = "NO SE PUEDE GRABAR EL CODIGO ACCIONES YA EXISTE.";
            public const string EX_OBJETIVOS_INSTITUCIONALES_ID_ACCIONES = "NO SE PUEDE GRABAR ID ACCIONES ID YA EXISTE.";

            public const string EX_CATEGORIAPRESUPUESTAL_CODIGO_OBJETIVOS = "NO SE PUEDE GRABAR EL CODIGO PRESUPUESTAL. YA EXISTE.";
            public const string EX_CATEGORIAPRESUPUESTAL_ID_OBJETIVOS = "NO SE PUEDE GRABAR ID PRESUPUESTAL. ID YA EXISTE.";

            public const string EX_DIVISIONFUNCIONAL_CODIGO = "NO SE PUEDE GRABAR EL CODIGO DE DIVISION FUNCIONAL. YA EXISTE.";
            public const string EX_DIVISIONFUNCIONAL_ID = "NO SE PUEDE GRABAR ID DIVISION FUNCIONAL. ID YA EXISTE.";

            public const string EX_GRUPOFUNCIONAL_CODIGO = "NO SE PUEDE GRABAR EL CODIGO DEL GRUPO FUNCIONAL. YA EXISTE.";
            public const string EX_GRUPOFUNCIONAL_ID = "NO SE PUEDE GRABAR ID CODIGO FUNCIONAL. ID YA EXISTE.";

            public const string EX_UNIDADMEDIDA_CODIGO = "NO SE PUEDE GRABAR EL CODIGO DE LA UNIDAD MEDIDA. YA EXISTE.";
            public const string EX_UNIDADMEDIDA_ID = "NO SE PUEDE GRABAR ID CODIGO DE LA UNIDAD MEDIDA. ID YA EXISTE.";

            public const string EX_FINALIDAD_CODIGO = "NO SE PUEDE GRABAR EL CODIGO DE LA FINALIDAD. YA EXISTE.";
            public const string EX_FINALIDAD_ID = "NO SE PUEDE GRABAR ID CODIGO DE LA FINALIDAD. ID YA EXISTE.";

            public const string EX_PRODUCTO_CODIGO = "NO SE PUEDE GRABAR EL CODIGO DE LA PRODUCTO. YA EXISTE.";
            public const string EX_PRODUCTO_ID = "NO SE PUEDE GRABAR ID CODIGO DE LA PRODUCTO. ID YA EXISTE.";

            public const string EX_PROGACTIVIDADES_CODIGO = "NO SE PUEDE GRABAR EL CODIGO DE LA PROG. ACTIVIDADES. YA EXISTE.";
            public const string EX_PROGACTIVIDADES_ID = "NO SE PUEDE GRABAR ID CODIGO DE LA PROG. ACTIVIDADES. ID YA EXISTE.";

            public const string EX_PROGTAREAS_CODIGO = "NO SE PUEDE GRABAR EL CODIGO DE LA PROG. TAREAS. YA EXISTE.";
            public const string EX_PROGTAREAS_ID = "NO SE PUEDE GRABAR ID CODIGO DE LA PROG. TAREAS. ID YA EXISTE.";

            public const string EX_PROGTAREAS_UNDMEDIDA = "NO SE PUEDE GRABAR LA ACCION DE TAREA. UNIDAD DE MEDIDA NO ES CORRECTA.";

            #endregion

            #region FORMATO
            public const string EX_FORMATO_ID_FORMATO_REQUIRED = "SE REQUIERE ID DE FORMATO PARA REALIZAR LA ACCIÓN.";
            public const string EX_FORMATO_NOMBRE_REQUIRED = "SE REQUIERE NOMBRE DEL FORMATO PARA REALIZAR LA ACCIÓN.";
            public const string EX_FORMATO_DESCRIPCION_REQUIRED = "SE REQUIERE DESCRIPCION DEL FORMATO PARA REALIZAR LA ACCIÓN.";
            public const string EX_FORMATO_TIPO_PESO_REQUIRED = "SE REQUIERE EL TIPO DE PESO PARA CALIFICACIÓN DEL FORMATO PARA REALIZAR LA ACCIÓN.";

            public const string EX_FORMATO_REGISTRO_DP = "NO SE PUEDE REALIZAR LA ACCIÓN. LA PERSONA SELECCIONA PARA FORMATO YA SE ENCUENRA REGISTRADA.";
            public const string EX_FORMATO_REGISTRO_ACTUAL_DP = "NO SE PUEDE REALIZAR LA ACCIÓN. YA EXISTE UN FORMATO(A) SELECCIONADO COMO ACTUAL.";
            public const string EX_FORMATO_NOT_FOUND = "NO SE PUEDE REALIZAR LA ACCIÓN. NO SE ENCONTRO EL REGISTRO DEL FORMATO SELECCIONADO.";


            #endregion

            //#region GENERICOS
            public const string EX_GRAL_NO_ACCESS = "UD NO TIENE PERMISOS PARA ACCEDER AL SERVICIO. COMUNÍQUESE CON EL ADMINISTRADOR.";
            public const string EX_GRAL_PROFILE_NO_ACCESS = "EL ROL DE LA SESION INICIADA NO TIENE PRIVILEGIOS PARA ACCEDER AL SERVICIO. COMUNÍQUESE CON EL ADMINISTRADOR.";
            public const string EX_GRAL_REQUEST_REQUIRED_ROL_SESION = "EL PARAMETRO PERSONAL ROL DE SESSION ES REQUERIDO";
             

            #region DOCUMENTOS ADJUNTOS
            public const string EX_DOCUMENTO_ADJUNTO_ID_REQUIRED = "NO SE PUDO REALIZAR LA ACCION. EL ID DEL DOCUMENTO ES REQUERIDO.";
            public const string EX_DOCUMENTO_ADJUNTO_ID_TIPO_REQUIRED = "NO SE PUDO REALIZAR LA ACCION. EL TIPO DE DOCUMENTO ES REQUERIDO.";
            public const string EX_DOCUMENTO_ADJUNTO_COMENTARIO_OBS_REQUIRED = "NO SE PUDO REALIZAR LA ACCION. EL COMENTARIO/OBSERVACIÓN ES REQUERIDO.";

            public const string EX_DOCUMENTO_ADJUNTO_ID_SUBTIPO_REQUIRED = "NO SE PUDO REALIZAR LA ACCION. EL SUBTIPO DE DOCUMENTO ES REQUERIDO.";
            public const string EX_DOCUMENTO_ADJUNTO_DOCUMENTO_REQUIRED = "NO SE PUDO REALIZAR LA ACCION. EL DOCUMENTO ES REQUERIDO.";
            public const string EX_DOCUMENTO_ADJUNTO_INSERT_NOOK = "NO SE PUDO REALIZAR LA ACCION. EL DOCUMENTO NO SE INSERTO.";
            public const string EX_DOCUMENTO_ADJUNTO_REQUIRED = "NO SE PUDO REALIZAR LA ACCION. LOS DOCUMENTOS ADJUNTOS SON REQUERIDOS.";
            public const string EX_DOCUMENTO_ADJUNTO_IMPORTE_SUMA_REQUIRED = "NO SE PUDO REALIZAR LA ACCION. LA SUMA DE LOS IMPORTES DEBEN SER MAYORES A 0.";
            public const string EX_DOCUMENTO_ADJUNTO_IMPORTE_SUMA_MAYOR_REQUIRED = "NO SE PUDO REALIZAR LA ACCION. LA SUMA DE LOS IMPORTES DEBEN SER MENOR O IGUAL AL MONTO POR RENDIR.";
            public const string EX_DOCUMENTO_ADJUNTO_ESTADO_OBS_NOOK = "NO SE PUDO REALIZAR LA ACCION. SE HAN ENCONTRADO DOCUMENTOS EN ESTADO OBSERVADO.";

            public const string EX_DOCUMENTO_ADJUNTO_ESTADO_NOOK = "NO SE PUDO REALIZAR LA ACCION. EL ESTADO ACTUAL DEL DOCUMENTO NO ES EL REQUERDO.";
            public const string EX_DOCUMENTO_ADJUNTO_NOT_FOUND = "NO SE PUDO REALIZAR LA ACCION. NO SE ENCONTRO EL DOCUMENTO.";

            #endregion

            #region ANIO
            public const string EX_ANIOS_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR  AÑO. LA DESCRIPCION DEL AÑO ES REQUERIDO";
            public const string EX_ANIOS_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR AÑO. ID DEL AÑO ES REQUERIDO";
            public const string EX_ANIOS_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR AÑO. ID DEL AÑO ES REQUERIDO";

            #endregion

            #region FUNCION
            public const string EX_FUNCION_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR  FUNCION. LA DESCRIPCION DE LA FUNCION ES REQUERIDO";            
            public const string EX_FUNCION_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR FUNCION. ID DE LA FUNCION ES REQUERIDO";
            public const string EX_FUNCION_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR FUNCION. ID DE LA FUNCION ES REQUERIDO";

            #endregion

            #region PROGRAMA
            public const string EX_PROGRAMA_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR PROGRAMA. LA DESCRIPCION DEL PROGRAMA ES REQUERIDO";
            public const string EX_PROGRAMA_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR PROGRAMA. ID DEL PROGRAMA ES REQUERIDO";
            public const string EX_PROGRAMA_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR PROGRAMA. ID DEL PROGRAMA ES REQUERIDO";

            #endregion

            #region SUBPROGRAMA
            public const string EX_SUBPROGRAMA_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR SUBPROGRAMA. LA DESCRIPCION DEL SUBPROGRAMA ES REQUERIDO";
            public const string EX_SUBPROGRAMA_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR SUBPROGRAMA. ID DEL SUBPROGRAMA ES REQUERIDO";
            public const string EX_SUBPROGRAMA_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR SUBPROGRAMA. ID DEL SUBPROGRAMA ES REQUERIDO";

            #endregion

            #region ESPECIFICA DEL GASTO
            public const string EX_ESPECIFICA_GASTO_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR LA ESPECIFICA DEL GASTO. LA DESCRIPCION DE LA ESPECIFICA ES REQUERIDO";
            public const string EX_ESPECIFICA_GASTO_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR LA ESPECIFICA DEL GASTO. ID DE LA ESPECIFICA ES REQUERIDO";
            public const string EX_ESPECIFICA_GASTO_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR LA ESPECIFICA_GASTO. ID DE LA ESPECIFICA ES REQUERIDO";

            #endregion

            #region COMPONENTE
            public const string EX_COMPONENTE_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR COMPONENTE. LA DESCRIPCION DEL COMPONENTE ES REQUERIDO";
            public const string EX_COMPONENTE_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR COMPONENTE. ID DEL COMPONENTE ES REQUERIDO";
            public const string EX_COMPONENTE_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR COMPONENTE. ID DEL COMPONENTE ES REQUERIDO";

            #endregion

            #region ACTIVIDAD
            public const string EX_ACTIVIDAD_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR ACTIVIDAD. LA DESCRIPCION DE LA ACTIVIDAD ES REQUERIDO";
            public const string EX_ACTIVIDAD_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR ACTIVIDAD. ID DE LA ACTIVIDAD ES REQUERIDO";
            public const string EX_ACTIVIDAD_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR ACTIVIDAD. ID DE LA ACTIVIDAD ES REQUERIDO";

            #endregion

            #region META
            public const string EX_META_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR META. LA DESCRIPCION DE LA META ES REQUERIDO";
            public const string EX_META_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR META. ID DE LA META ES REQUERIDO";
            public const string EX_META_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR META. ID DE LA META ES REQUERIDO";

            #endregion

            #region PAISES
            public const string EX_PAIS_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR PAIS. EL NOMBRE DEL PAIS ES REQUERIDO";
            public const string EX_PAIS_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR PAIS. ID DEL PAIS ES REQUERIDO";
            public const string EX_PAIS_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR PAIS. ID DEL PAIS ES REQUERIDO";
            #endregion

            #region UBIGEO DEPARTAMENTO
            public const string EX_UBIGEO_DPTO_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR DEPARTAMENTO. LA DESCRIPCION DEL DEPARTAMENTO ES REQUERIDO";
            public const string EX_UBIGEO_DPTO_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR DEPARTAMENTO. ID DEL DEPARTAMENTO ES REQUERIDO";
            public const string EX_UBIGEO_DPTO_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR DEPARTAMENTO. ID DEL DEPARTAMENTO ES REQUERIDO";
            #endregion

            #region UBIGEO PROVINCIA
            public const string EX_UBIGEO_PROVINCIA_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR PROVINCIA. LA DESCRIPCION DE LA PROVINCIA ES REQUERIDO";
            public const string EX_UBIGEO_PROVINCIA_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR PROVINCIA. ID DE LA PROVINCIA ES REQUERIDO";
            public const string EX_UBIGEO_PROVINCIA_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR PROVINCIA. ID DE LA PROVINCIA ES REQUERIDO";
            #endregion

            #region UBIGEO DISTRITO
            public const string EX_UBIGEO_DISTRITO_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR DISTRITO. LA DESCRIPCION DEL DISTRITO ES REQUERIDO";
            public const string EX_UBIGEO_DISTRITO_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR DISTRITO. ID DEL DISTRITO ES REQUERIDO";
            public const string EX_UBIGEO_DISTRITO_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR DISTRITO. ID DEL DISTRITO ES REQUERIDO";
            #endregion


            #region UBIGEO_EXTERIOR
            public const string EX_UBIGEO_EXTERIOR_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR EL UBIGEO EXTERIOR . LA DESCRIPCION DEL NOMBRE OSE ES REQUERIDO";
            public const string EX_UBIGEO_EXTERIOR_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR UBIGEO_EXTERIOR. ID DEL UBIGEO_EXTERIOR ES REQUERIDO";
            public const string EX_UBIGEO_EXTERIOR_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR UBIGEO_EXTERIOR. ID DEL UBIGEO_EXTERIOR ES REQUERIDO";
            #endregion

            #region TIPODECAMBIO
            public const string EX_TIPODECAMBIO_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR TIPO DE CAMBIO. LA NOMBRE DE LA MONEDA ES REQUERIDO";
            public const string EX_TIPODECAMBIO_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR TIPO DE CAMBIO. ID DEL TIPO DE CAMBIO ES REQUERIDO";
            public const string EX_TIPODECAMBIO_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR TIPO DE CAMBIO. ID DEL TIPO DE CAMBIO ES REQUERIDO";
            #endregion

            #region CCOSTOS
            public const string EX_CCOSTOS_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR CENTRO COSTOS. LA DESCRIPCION DEL CENTRO COSTOS ES REQUERIDO";
            public const string EX_CCSOTOS_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR CENTRO COSTOS. ID DEL CENTRO COSTOS ES REQUERIDO";
            public const string EX_CCOSTOS_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR CENTRO COSTOS. ID DEL CENTRO COSTOS ES REQUERIDO";
            #endregion

            #region CALENDARIO
            public const string EX_CALENDARIO_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR CALENDARIO. LA DESCRIPCION DEL CALENDARIO ES  REQUERIDO";
            public const string EX_CALENDARIO_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR CALENDARIO. ID DEL CALENDARIO ES REQUERIDO";
            public const string EX_CALENDARIO_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR CALENDARIO. ID DEL CALENDARIO ES REQUERIDO";
            #endregion

            #region POLITICAS
            public const string EX_POLITICAS_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR POLITICAS. LA DESCRIPCION DE LA POLITICA ES REQUERIDO";
            public const string EX_POLITICAS_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR POLITICAS. ID DE POLITICAS ES REQUERIDO";
            public const string EX_POLITICAS_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR POLITICAS. ID DE POLITICAS ES REQUERIDO";
            public const string EX_POLITICAS_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR POLITICAS. EL AÑO DEL POLITICAS ES REQUERIDO";
            #endregion

            #region OBJETIVOS
            public const string EX_OBJETIVOS_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR OBJETIVO SECTORIAL. LA DESCRIPCION DEL OBJETIVO SECTORIAL ES REQUERIDO";
            public const string EX_OBJETIVOS_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR OBJETIVO SECTORIAL. ID DEL OBJETIVO SECTORIAL ES REQUERIDO";
            public const string EX_OBJETIVOS_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR OBJETIVO SECTORIAL. ID DEL OBJETIVOS SECTORIAL ES REQUERIDO";
            public const string EX_OBJETIVOS_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR OBJETIVO SECTORIAL. EL AÑO DEL OBJETIVO SECTORIAL ES REQUERIDO";
            #endregion

            #region ACCIONES
            public const string EX_ACCIONES_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR ACCIONES. LA DESCRIPCION DE LA ACCION ES REQUERIDO";
            public const string EX_ACCIONES_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR ACCIONES. ID DE LA ACCION ES REQUERIDO";
            public const string EX_ACCIONES_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR ACCIONES. ID DE LA ACCION ES REQUERIDO";
            public const string EX_ACCIONES_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR ACCIONES. EL AÑO DE LA ACCION ES REQUERIDO";
            #endregion

            #region OBJETIVOS INSTITUCIONALES
            public const string EX_OBJ_INSTITUCIONALES_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR EL OBJETIVO INSTITUCIONAL. LA DESCRIPCION DEL OBJETIVO INSTITUCIONAL ES REQUERIDO";
            public const string EX_OBJ_INSTITUCIONALES_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR EL OBJETIVO INSTITUCIONAL. ID DEL OBJETIVO INSTITUCIONAL ES REQUERIDO";
            public const string EX_OBJ_INSTITUCIONALES_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR EL OBJETIVO INSTITUCIONAL. ID DEL OBJETIVO INSTITUCIONAL ES REQUERIDO";
            public const string EX_OBJ_INSTITUCIONALES_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR OBJETIVO INSTITUCIONAL. EL AÑO DEL OBJETIVO ES REQUERIDO";
            #endregion

            #region ACCIONES INSTITUCIONALES
            public const string EX_ACCIONES_INSTITUCIONALES_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR ACCIONES INSTITUCIONALES. LA DESCRIPCION DE ACCIONES INSTITUCIONALES ES REQUERIDO";
            public const string EX_ACCIONES_INSTITUCIONALES_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR ACCIONES INSTITUCIONALES. ID DE ACCIONES INSTITUCIONALES  ES REQUERIDO";
            public const string EX_ACCIONES_INSTITUCIONALES_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR ACCIONES INSTITUCIONALES. ID DE ACCIONES INSTITUCIONALES ES REQUERIDO";
            public const string EX_ACCIONES_INSTITUCIONALES_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR ACCIONES INSTITUCIONALES. EL AÑO DE ACCIONES INSTITUCIONALES ES REQUERIDO";
            #endregion

            #region FASESPOI
            public const string EX_FASESPOI_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR FASES POI. LA DESCRIPCION DE LA FASE POI ES REQUERIDO";
            public const string EX_FASESPOI_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR FASES POI. ID DE LA FASE POI ES REQUERIDO";
            public const string EX_FASESPOI_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR FASES POI. ID DE LA FASE POI ES REQUERIDO";
            public const string EX_FASESPOI_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR FASES POI. EL AÑO DE LA FASE POI ES REQUERIDO";
            #endregion

            #region AEICENTROCOSTOS            
            public const string EX_AEICENTROCOSTOS_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR AEI CENTRO COSTOS. ID DE LA ACCION ES REQUERIDO";
            #endregion

            #region CATEGORIA PRESUPUESTAL
            public const string EX_CATEGORIA_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR CATEGORIA. LA DESCRIPCION DE LA CATEGORIA PRESUPUESTAL ES REQUERIDO";
            public const string EX_CATEGORIA_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR CATEGORIA. ID DE LA CATEGORIA PRESUPUESTAL ES REQUERIDO";
            public const string EX_CATEGORIA_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR CATEGORIA. ID DE LA CATEGORIA PRESUPUESTAL ES REQUERIDO";
            public const string EX_CATEGORIA_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR CATEGORIA. EL AÑO DE LA CATEGORIA PRESUPUESTAL ES REQUERIDO";
            #endregion

            #region AEICATEGORIA            
            public const string EX_AEICATEGORIA_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR AEI CATEGORIA PRESUPUESTAL. ID DE LA CATEGORIA PRESUPUESTAL ES REQUERIDO";
            #endregion

            #region DIVISIONFUNCIONAL
            public const string EX_DIVISIONFUNCIONAL_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR DIVISION FUNCIONAL. LA DESCRIPCION DE LA DIVISION FUNCIONAL ES REQUERIDO";
            public const string EX_DIVISIONFUNCIONAL_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR DIVISION FUNCIONAL. ID DE LA DIVISION FUNCIONAL ES REQUERIDO";
            public const string EX_DIVISIONFUNCIONAL_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR DIVISION FUNCIONAL. ID DE LA DIVISION FUNCIONAL ES REQUERIDO";
            public const string EX_DIVISIONFUNCIONAL_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR DIVISION FUNCIONAL. EL AÑO DE LA DIVISION FUNCIONAL ES REQUERIDO";
            #endregion

            #region GRUPOFUNCIONAL
            public const string EX_GRUPOFUNCIONAL_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR GRUPO FUNCIONAL. LA DESCRIPCION DE LA GRUPO FUNCIONAL ES REQUERIDO";
            public const string EX_GRUPOFUNCIONAL_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR GRUPO FUNCIONAL. ID DE LA GRUPO FUNCIONAL ES REQUERIDO";
            public const string EX_GRUPOFUNCIONAL_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR GRUPO FUNCIONAL. ID DE LA GRUPO FUNCIONAL ES REQUERIDO";
            public const string EX_GRUPOFUNCIONAL_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR GRUPO FUNCIONAL. EL AÑO DE LA GRUPO FUNCIONAL ES REQUERIDO";
            #endregion

            #region UNIDADMEDIDA
            public const string EX_UNIDADMEDIDA_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR UNIDAD MEDIDA. LA DESCRIPCION DE LA UNIDAD MEDIDA ES REQUERIDO";
            public const string EX_UNIDADMEDIDA_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR UNIDAD MEDIDA. ID DE LA UNIDAD MEDIDA ES REQUERIDO";
            public const string EX_UNIDADMEDIDA_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR UNIDAD MEDIDA. ID DE LA UNIDAD MEDIDA ES REQUERIDO";
            public const string EX_UNIDADMEDIDA_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR UNIDAD MEDIDA. EL AÑO DE LA UNIDAD MEDIDA ES REQUERIDO";
            #endregion

            #region FINALIDAD
            public const string EX_FINALIDAD_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR FINALIDAD. LA DESCRIPCION DE LA FINALIDAD ES REQUERIDO";
            public const string EX_FINALIDAD_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR FINALIDAD. ID DE LA FINALIDAD ES REQUERIDO";
            public const string EX_FINALIDAD_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR FINALIDAD. ID DE LA FINALIDAD ES REQUERIDO";
            public const string EX_FINALIDAD_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR FINALIDAD. EL AÑO DE LA FINALIDAD ES REQUERIDO";
            #endregion

            #region PRODUCTO
            public const string EX_PRODUCTO_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR PRODUCTO. LA DESCRIPCION DE LA PRODUCTO ES REQUERIDO";
            public const string EX_PRODUCTO_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR PRODUCTO. ID DE LA PRODUCTO ES REQUERIDO";
            public const string EX_PRODUCTO_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR PRODUCTO. ID DE LA PRODUCTO ES REQUERIDO";
            public const string EX_PRODUCTO_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR PRODUCTO. EL AÑO DE LA PRODUCTO ES REQUERIDO";
            #endregion

            #region PROG-ACTIVIDADES
            public const string EX_PROGACTIVIDADES_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR PROG. ACTIVIDADES. LA DESCRIPCION DE LA PROG. ACTIVIDADES ES REQUERIDO";
            public const string EX_PROGACTIVIDADES_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR PROG. ACTIVIDADES. ID DE LA PROG. ACTIVIDADES ES REQUERIDO";
            public const string EX_PROGACTIVIDADES_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR PROG. ACTIVIDADES. ID DE LA PROG. ACTIVIDADES ES REQUERIDO";
            public const string EX_PROGACTIVIDADES_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR PROG. ACTIVIDADES. EL AÑO DE LA PROG. ACTIVIDADES ES REQUERIDO";
            public const string EX_PROGACTIVIDADES_OBSERVADO_REQUIRED = "NO SE PUEDE REGISTRAR LA OBSERVACION. LA DESCRIPCION DE LA OBSERVACION EN ACTIVIDADES ES REQUERIDO";
            #endregion

            #region PROG-TAREAS
            public const string EX_PROGTAREAS_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR PROG. TAREAS. LA DESCRIPCION DE LA PROG. TAREAS ES REQUERIDO";
            public const string EX_PROGTAREAS_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR PROG. TAREAS. ID DE LA PROG. TAREAS ES REQUERIDO";
            public const string EX_PROGTAREAS_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR PROG. TAREAS. ID DE LA PROG. TAREAS ES REQUERIDO";
            public const string EX_PROGTAREAS_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR PROG. TAREAS. EL AÑO DE LA PROG. TAREAS ES REQUERIDO";
            #endregion

            #region PROG-ACCIONES
            public const string EX_PROGACCIONES_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR PROG. ACCIONES. LA DESCRIPCION DE LA PROG. ACCIONES ES REQUERIDO";
            public const string EX_PROGACCIONES_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR PROG. ACCIONES. ID DE LA PROG. ACCIONES ES REQUERIDO";
            public const string EX_PROGACCIONES_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR PROG. ACCIONES. ID DE LA PROG. ACCIONES ES REQUERIDO";
            public const string EX_PROGACCIONES_AÑO_REQUIRED = "NO SE PUEDE REGISTRAR PROG. ACCIONES. EL AÑO DE LA PROG. ACCIONES ES REQUERIDO";
            #endregion

            #region BIENES SERVICIOS
            public const string EX_BIENESSERVICIOS_DESCRIPCION_REQUIRED = "NO SE PUEDE REGISTRAR EL BIEN. LA DESCRIPCION DEL BIEN ES REQUERIDO";
            public const string EX_BIENESSERVICIOS_ACTUALIZAR_ID_REQUIRED = "NO SE PUEDE ACTUALIZAR EL BIEN. ID DEL BIEN ES REQUERIDO";
            public const string EX_BIENESSERVICIOS_ELIMINAR_ID_REQUIRED = "NO SE PUEDE ELIMINAR EL BIEN. ID DEL BIEN ES REQUERIDO";
            #endregion
        }

        public struct MensajesOK
        {
            public const string M07 = "OPERACIÓN REALIZADA DE FORMA EXITOSA";
           
            public const string M01_USUARIOROL_DELETE_OK = "ACCESO ELIMINADO CORRECTAMENTE.";
            public const string M01_USUARIOROL_UPDATE_OK = "ACCESO ACTUALIZADO CORRECTAMENTE.";
            public const string M01_USUARIOROL_INSERT_OK = "ACCESO REGISTRADO CORRECTAMENTE.";


            public const string M01_USUARIO_UPDATE_OK = "PERSONAL ACTUALIZADO CORRECTAMENTE.";
            public const string M01_USUARIO_INSERT_OK = "PERSONAL REGISTRADO CORRECTAMENTE.";

            public const string M01_CATALOGO_UPDATE_OK = "CATÁLOGO ACTUALIZADO CORRECTAMENTE.";
            public const string M01_CATALOGO_INSERT_OK = "CATÁLOGO REGISTRADO CORRECTAMENTE.";
            public const string M01_CATALOGO_DELETE_OK = "CATÁLOGO ELIMINADO CORRECTAMENTE.";

            public const string M01_CATALOGOITEM_UPDATE_OK = "CATÁLOGO ITEM ACTUALIZADO CORRECTAMENTE.";
            public const string M01_CATALOGOITEM_INSERT_OK = "CATÁLOGO ITEM REGISTRADO CORRECTAMENTE.";
            public const string M01_CATALOGOITEM_DELETE_OK = "CATÁLOGO ITEM ELIMINADO CORRECTAMENTE.";

           
            public const string M01_ROL_UPDATE_OK = "ROL ACTUALIZADO CORRECTAMENTE.";
            public const string M01_ROL_INSERT_OK = "ROL REGISTRADO CORRECTAMENTE.";
            public const string M01_ROL_DELETE_OK = "ROL ELIMINADO CORRECTAMENTE.";

            public const string M01_GRUPOATENCION_UPDATE_OK = "GRUPO - PAIS ACTUALIZADO CORRECTAMENTE.";
            public const string M01_GRUPOATENCION_INSERT_OK = "GRUPO - PAIS REGISTRADO CORRECTAMENTE.";
            public const string M01_GRUPOATENCION_DELETE_OK = "GRUPO - PAIS ELIMINADO CORRECTAMENTE.";

            public const string M01_ACCESO_UPDATE_OK = "ACCESO ACTUALIZADO CORRECTAMENTE.";
            public const string M01_ACCESO_INSERT_OK = "ACCESO REGISTRADO CORRECTAMENTE.";
            public const string M01_ACCESO_DELETE_OK = "ACCESO ELIMINADO CORRECTAMENTE.";

            public const string M01_CLASIFICACIONPERSONAL_OK = "CLASIFICACION PERSONAL REGISTRADO CORRECTAMENTE";
            public const string M01_CLASIFICACIONPERSONAL_UPDATE_OK = "CLASIFICACION PERSONAL ACTUALIZADO CORRECTAMENTE";
            public const string M01_CLASIFICACIONPERSONAL_DELETE_OK = "CLASIFICACION PERSONAL ELIMINADO CORRECTAMENTE";

            public const string M01_PROYECTOMCC_INSERT_OK = "PROYECTO MCC REGISTRADO CORRECTAMENTE.";
            public const string M01_PROYECTOMCC_UPDATE_OK = "PROYECTO MCC ACTUALIZADO CORRECTAMENTE.";
            public const string M01_PROYECTOMCC_DELETE_OK = "PROYECTO MCC ELIMINADO CORRECTAMENTE.";

            public const string M01_ORDEN_OK = "SE CAMBIO EL ORDEN CORRECTAMENTE";

            public const string M01_PROYECTO_CARGO_REQUISITO_UPDATE_OK = "PROYECTO CARGO REQUISITO ACTUALIZADO CORRECTAMENTE.";

            public const string M01_PROYECTOEO_INSERT_OK = "PROYECTO EO REGISTRADO CORRECTAMENTE.";
            public const string M01_PROYECTOEO_UPDATE_OK = "PROYECTO EO ACTUALIZADO CORRECTAMENTE.";
            public const string M01_PROYECTOEO_DELETE_OK = "PROYECTO EO ELIMINADO CORRECTAMENTE.";

            public const string M01_UNIDAD_ORGANIZACIONAL_CARGO_DELETE_OK = "UNIDAD ORGANIZACIONAL CARGO ELIMINADO CORRECTAMENTE.";
            public const string M01_UNIDAD_ORGANIZACIONAL_CARGO_UPDATE_OK = "UNIDAD ORGANIZACIONAL CARGO ACTUALIZADO CORRECTAMENTE";

            public const string M01_ORGANISMO_UPDATE_OK = "ORGANISMO ACTUALIZADO CORRECTAMENTE";
            public const string M01_ORGANISMO_DELETE_OK = "ORGANISMO ELIMINADO CORRECTAMENTE";
            #region DOCUMENTOS ADJUNTOS
            public const string M01_RESPUESTA_INSERT_OK = "RESPUESTAS REGISTRADAS CORRECTAMENTE.";
            public const string M01_RESPUESTA_UPDATE_OK = "RESPUESTAS ACTUALIZADAS CORRECTAMENTE.";
            #endregion

            #region PERSONA
            public const string M01_PERSONA_INSERT_OK = "PERSONA REGISTRADA CORRECTAMENTE.";
            public const string M01_PERSONA_UPDATE_OK = "PERSONA ACTUALIZADA CORRECTAMENTE.";
            public const string M01_PERSONA_DELETE_OK = "PERSONA ELIMINADA CORRECTAMENTE.";
            #endregion

            #region ANIOS
            public const string M01_ANIOS_INSERT_OK = "AÑO REGISTRADO CORRECTAMENTE.";
            public const string M01_ANIOS_UPDATE_OK = "AÑO ACTUALIZADO CORRECTAMENTE.";
            public const string M01_ANIOS_DELETE_OK = "AÑO ELIMINADO CORRECTAMENTE.";
            #endregion

            #region FUNCION
            public const string M01_FUNCION_INSERT_OK = "FUNCION REGISTRADA CORRECTAMENTE.";
            public const string M01_FUNCION_UPDATE_OK = "FUNCION ACTUALIZADA CORRECTAMENTE.";
            public const string M01_FUNCION_DELETE_OK = "FUNCION ELIMINADA CORRECTAMENTE.";
            #endregion

            #region PROGRAMA
            public const string M01_PROGRAMA_INSERT_OK = "PROGRAMA REGISTRADO CORRECTAMENTE.";
            public const string M01_PROGRAMA_UPDATE_OK = "PROGRAMA ACTUALIZADO CORRECTAMENTE.";
            public const string M01_PROGRAMA_DELETE_OK = "PROGRAMA ELIMINADO CORRECTAMENTE.";
            #endregion

            #region SUBPROGRAMA
            public const string M01_SUBPROGRAMA_INSERT_OK = "SUBPROGRAMA REGISTRADO CORRECTAMENTE.";
            public const string M01_SUBPROGRAMA_UPDATE_OK = "SUBPROGRAMA ACTUALIZADO CORRECTAMENTE.";
            public const string M01_SUBPROGRAMA_DELETE_OK = "SUBPROGRAMA ELIMINADO CORRECTAMENTE.";
            #endregion

            #region COMPONENTE
            public const string M01_COMPONENTE_INSERT_OK = "COMPONENTE REGISTRADO CORRECTAMENTE.";
            public const string M01_COMPONENTE_UPDATE_OK = "COMPONENTE ACTUALIZADO CORRECTAMENTE.";
            public const string M01_COMPONENTE_DELETE_OK = "COMPONENTE ELIMINADO CORRECTAMENTE.";
            #endregion

            #region ESPECIFICA
            public const string M01_ESPECIFICA_GASTO_INSERT_OK = "ESPECIFICA DEL GASTO REGISTRADA CORRECTAMENTE.";
            public const string M01_ESPECIFICA_GASTO_UPDATE_OK = "ESPECIFICA DEL GASTO ACTUALIZADA CORRECTAMENTE.";
            public const string M01_ESPECIFICA_GASTO_DELETE_OK = "ESPECIFICA DEL GASTO ELIMINADA CORRECTAMENTE.";
            #endregion

            #region ACTIVIDAD
            public const string M01_ACTIVIDAD_INSERT_OK = "ACTIVIDAD REGISTRADA CORRECTAMENTE.";
            public const string M01_ACTIVIDAD_UPDATE_OK = "ACTIVIDAD ACTUALIZADA CORRECTAMENTE.";
            public const string M01_ACTIVIDAD_DELETE_OK = "ACTIVIDAD ELIMINADA CORRECTAMENTE.";
            #endregion

            #region META
            public const string M01_META_INSERT_OK = "META REGISTRADA CORRECTAMENTE.";
            public const string M01_META_UPDATE_OK = "META ACTUALIZADA CORRECTAMENTE.";
            public const string M01_META_DELETE_OK = "META ELIMINADA CORRECTAMENTE.";
            #endregion

            #region PAIS
            public const string M01_PAIS_INSERT_OK = "PAIS REGISTRADO CORRECTAMENTE.";
            public const string M01_PAIS_UPDATE_OK = "PAIS ACTUALIZADO CORRECTAMENTE.";
            public const string M01_PAIS_DELETE_OK = "PAIS ELIMINADO CORRECTAMENTE.";
            #endregion

            #region UBIGEO DEPARTAMENTO
            public const string M01_UBIGEO_DPTO_INSERT_OK = "DEPARTAMENTO REGISTRADO CORRECTAMENTE.";
            public const string M01_UBIGEO_DPTO_UPDATE_OK = "DEPARTAMENTO ACTUALIZADO CORRECTAMENTE.";
            public const string M01_UBIGEO_DPTO_DELETE_OK = "DEPARTAMENTO ELIMINADO CORRECTAMENTE.";
            #endregion

            #region UBIGEO PROVINCIA
            public const string M01_UBIGEO_PROVINCIA_INSERT_OK = "PROVINCIA REGISTRADA CORRECTAMENTE.";
            public const string M01_UBIGEO_PROVINCIA_UPDATE_OK = "PROVINCIA ACTUALIZADA CORRECTAMENTE.";
            public const string M01_UBIGEO_PROVINCIA_DELETE_OK = "PROVINCIA ELIMINADA CORRECTAMENTE.";
            #endregion

            #region UBIGEO DISTRITO
            public const string M01_UBIGEO_DISTRITO_INSERT_OK = "DISTRITO REGISTRADO CORRECTAMENTE.";
            public const string M01_UBIGEO_DISTRITO_UPDATE_OK = "DISTRITO ACTUALIZADO CORRECTAMENTE.";
            public const string M01_UBIGEO_DISTRITO_DELETE_OK = "DISTRITO ELIMINADO CORRECTAMENTE.";
            #endregion

            #region UBIGEO_EXTERIOR
            public const string M01_UBIGEO_EXTERIOR_INSERT_OK = "UBIGEO EXTERIOR REGISTRADO CORRECTAMENTE.";
            public const string M01_UBIGEO_EXTERIOR_UPDATE_OK = "UBIGEO_EXTERIOR ACTUALIZADO CORRECTAMENTE.";
            public const string M01_UBIGEO_EXTERIOR_DELETE_OK = "UBIGEO_EXTERIOR ELIMINADO CORRECTAMENTE.";
            #endregion

            #region TIODECAMBIO
            public const string M01_TIODECAMBIO_INSERT_OK = "TIO DE CAMBIO REGISTRADO CORRECTAMENTE.";
            public const string M01_TIODECAMBIO_UPDATE_OK = "TIO DE CAMBIO ACTUALIZADO CORRECTAMENTE.";
            public const string M01_TIODECAMBIO_DELETE_OK = "TIO DE CAMBIO ELIMINADO CORRECTAMENTE.";
            #endregion

            #region CCOSTOS
            public const string M01_CCOSTOS_INSERT_OK = "CENTRO DE COSTOS REGISTRADO CORRECTAMENTE.";
            public const string M01_CCOSTOS_UPDATE_OK = "CENTRO DE COSTOS ACTUALIZADO CORRECTAMENTE.";
            public const string M01_CCOSTOS_DELETE_OK = "CENTRO DE COSTOS ELIMINADO CORRECTAMENTE.";
            #endregion

            #region CALENDARIO
            public const string M01_CALENDARIO_INSERT_OK = "CALENDARIO REGISTRADO CORRECTAMENTE.";
            public const string M01_CALENDARIO_UPDATE_OK = "CALENDARIO ACTUALIZADO CORRECTAMENTE.";
            public const string M01_CALENDARIO_DELETE_OK = "CALENDARIO ELIMINADO CORRECTAMENTE.";
            #endregion

            #region POLITICAS
            public const string M01_POLITICAS_INSERT_OK = "POLITICA REGISTRADA CORRECTAMENTE.";
            public const string M01_POLITICAS_UPDATE_OK = "POLITICA ACTUALIZADA CORRECTAMENTE.";
            public const string M01_POLITICAS_DELETE_OK = "POLITICA ELIMINADO CORRECTAMENTE.";
            #endregion

            #region OBJETIVOS
            public const string M01_OBJETIVOS_INSERT_OK = "OBJETIVO SECTORIAL REGISTRADO CORRECTAMENTE.";
            public const string M01_OBJETIVOS_UPDATE_OK = "OBJETIVO SECTORIAL ACTUALIZADO CORRECTAMENTE.";
            public const string M01_OBJETIVOS_DELETE_OK = "OBJETIVO SECTORIAL ELIMINADO CORRECTAMENTE.";
            #endregion

            #region ACCIONES
            public const string M01_ACCIONES_INSERT_OK = "ACCION REGISTRADA CORRECTAMENTE.";
            public const string M01_ACCIONES_UPDATE_OK = "ACCION ACTUALIZADA CORRECTAMENTE.";
            public const string M01_ACCIONES_DELETE_OK = "ACCION ELIMINADA CORRECTAMENTE.";
            #endregion

            #region OBJETIVOS INSTITUCIOANAL
            public const string M01_OBJ_INSTITUCIOANAL_INSERT_OK = "OBJETIVO INSTITUCIOANAL REGISTRADO CORRECTAMENTE.";
            public const string M01_OBJ_INSTITUCIOANAL_UPDATE_OK = "OBJETIVO INSTITUCIOANAL ACTUALIZADO CORRECTAMENTE.";
            public const string M01_OBJ_INSTITUCIOANAL_DELETE_OK = "OBJETIVO INSTITUCIOANAL ELIMINADO CORRECTAMENTE.";
            #endregion

            #region ACCIONES INSTITUCIOANAL
            public const string M01_ACCIONES_INSTITUCIOANAL_INSERT_OK = "ACCION INSTITUCIOANAL REGISTRADA CORRECTAMENTE.";
            public const string M01_ACCIONES_INSTITUCIOANAL_UPDATE_OK = "ACCION INSTITUCIOANAL ACTUALIZADA CORRECTAMENTE.";
            public const string M01_ACCIONES_INSTITUCIOANAL_DELETE_OK = "ACCION INSTITUCIOANAL ELIMINADA CORRECTAMENTE.";
            #endregion

            #region FASESPOI
            public const string M01_FASESPOI_INSERT_OK = "FASES POI REGISTRADA CORRECTAMENTE.";
            public const string M01_FASESPOI_UPDATE_OK = "FASES POI ACTUALIZADA CORRECTAMENTE.";
            public const string M01_FASESPOI_DELETE_OK = "FASES POI ELIMINADA CORRECTAMENTE.";
            #endregion

            #region AEICENTROCOSTOS
            public const string M01_AEICENTROCOSTOS_INSERT_OK = "AEI CENTRO COSTOS REGISTRADA CORRECTAMENTE.";
            public const string M01_AEICENTROCOSTOS_UPDATE_OK = "AEI CENTRO COSTOS ACTUALIZADA CORRECTAMENTE.";
            public const string M01_AEICENTROCOSTOS_DELETE_OK = "AEI CENTRO COSTOS ELIMINADA CORRECTAMENTE.";
            #endregion

            #region CATEGORIA PRESUPUESTAL
            public const string M01_CATEGORIA_INSERT_OK = "CATEGORIA PRESUPUESTAL REGISTRADA CORRECTAMENTE.";
            public const string M01_CATEGORIA_UPDATE_OK = "CATEGORIA PRESUPUESTAL ACTUALIZADA CORRECTAMENTE.";
            public const string M01_CATEGORIA_DELETE_OK = "CATEGORIA PRESUPUESTAL ELIMINADA CORRECTAMENTE.";
            #endregion

            #region AEICATEGORIAPRESUPUESTAL
            public const string M01_AEICATEGORIAPRESUPUESTAL_INSERT_OK = "AEI CATEGORIA PRESUPUESTAL REGISTRADA CORRECTAMENTE.";
            public const string M01_AEICATEGORIAPRESUPUESTAL_UPDATE_OK = "AEI CATEGORIA PRESUPUESTAL ACTUALIZADA CORRECTAMENTE.";
            public const string M01_AEICATEGORIAPRESUPUESTAL_DELETE_OK = "AEI CATEGORIA PRESUPUESTAL ELIMINADA CORRECTAMENTE.";
            #endregion

            #region DIVISION_FUNCIONAL
            public const string M01_DIVISION_FUNCIONAL_INSERT_OK = "DIVISION FUNCIONAL REGISTRADA CORRECTAMENTE.";
            public const string M01_DIVISION_FUNCIONAL_UPDATE_OK = "DIVISION FUNCIONAL ACTUALIZADA CORRECTAMENTE.";
            public const string M01_DIVISION_FUNCIONAL_DELETE_OK = "DIVISION FUNCIONAL ELIMINADA CORRECTAMENTE.";
            #endregion

            #region GRUPO_FUNCIONAL
            public const string M01_GRUPO_FUNCIONAL_INSERT_OK = "GRUPO FUNCIONAL REGISTRADA CORRECTAMENTE.";
            public const string M01_GRUPO_FUNCIONAL_UPDATE_OK = "GRUPO FUNCIONAL ACTUALIZADA CORRECTAMENTE.";
            public const string M01_GRUPO_FUNCIONAL_DELETE_OK = "GRUPO FUNCIONAL ELIMINADA CORRECTAMENTE.";
            #endregion

            #region UNIDAD_MEDIDA
            public const string M01_UNIDAD_MEDIDA_INSERT_OK = "UNIDAD MEDIDA REGISTRADA CORRECTAMENTE.";
            public const string M01_UNIDAD_MEDIDA_UPDATE_OK = "UNIDAD MEDIDA ACTUALIZADA CORRECTAMENTE.";
            public const string M01_UNIDAD_MEDIDA_DELETE_OK = "UNIDAD MEDIDA ELIMINADA CORRECTAMENTE.";
            #endregion

            #region FINALIDAD
            public const string M01_FINALIDAD_INSERT_OK = "FINALIDAD REGISTRADA CORRECTAMENTE.";
            public const string M01_FINALIDAD_UPDATE_OK = "FINALIDAD ACTUALIZADA CORRECTAMENTE.";
            public const string M01_FINALIDAD_DELETE_OK = "FINALIDAD ELIMINADA CORRECTAMENTE.";
            #endregion

            #region PRODUCTO
            public const string M01_PRODUCTO_INSERT_OK = "PRODUCTO REGISTRADA CORRECTAMENTE.";
            public const string M01_PRODUCTO_UPDATE_OK = "PRODUCTO ACTUALIZADA CORRECTAMENTE.";
            public const string M01_PRODUCTO_DELETE_OK = "PRODUCTO ELIMINADA CORRECTAMENTE.";
            #endregion

            #region PROGACTIVIDADES
            public const string M01_PROGACTIVIDADES_INSERT_OK = "PROGACTIVIDADES REGISTRADA CORRECTAMENTE.";
            public const string M01_PROGACTIVIDADES_UPDATE_OK = "PROGACTIVIDADES ACTUALIZADA CORRECTAMENTE.";
            public const string M01_PROGACTIVIDADES_DELETE_OK = "PROGACTIVIDADES ELIMINADA CORRECTAMENTE.";
            #endregion

            #region PROGTAREAS
            public const string M01_PROGTAREAS_INSERT_OK = "PROGTAREAS REGISTRADA CORRECTAMENTE.";
            public const string M01_PROGTAREAS_UPDATE_OK = "PROGTAREAS ACTUALIZADA CORRECTAMENTE.";
            public const string M01_PROGTAREAS_DELETE_OK = "PROGTAREAS ELIMINADA CORRECTAMENTE.";
            #endregion

            #region PROGACCIONES
            public const string M01_PROGACCIONES_INSERT_OK = "PROGACCIONES REGISTRADA CORRECTAMENTE.";
            public const string M01_PROGACCIONES_UPDATE_OK = "PROGACCIONES ACTUALIZADA CORRECTAMENTE.";
            public const string M01_PROGACCIONES_DELETE_OK = "PROGACCIONES ELIMINADA CORRECTAMENTE.";
            #endregion

            #region BIENESSERVICIOS
            public const string M01_BIENESSERVICIOS_INSERT_OK = "EL BIEN SE REGISTRO CORRECTAMENTE.";
            public const string M01_BIENESSERVICIOS_UPDATE_OK = "EL BIEN SE ACTUALIZO CORRECTAMENTE.";
            public const string M01_BIENESSERVICIOS_DELETE_OK = "EL BIEN SE ELIMINADO CORRECTAMENTE.";
            #endregion

            public const string M01_LOGIN_OK = "PERSONAL REALIZO LOGGIN CON EXITO.";
            public const string M01_LOGOUT_OK = "PERSONAL REALIZO LOGOUT CON EXITO.";

        }

      
        public struct Estado
        {
            public const bool Activo = true;
            public const bool Inicial = false;
        }

        public struct APIDocumento
        {
            public const string SubirDocumento = "v2/tecnologia/util/documentos";
        }

        public struct APIPassport
        {
            public const string validacionLogin = "v1/rree/orh/oap/smeo/passport";

        }
        public struct CodigoCarpetaTipoDoc
        {
            public const string PROYECTO = "PJ";
            public const string TIPO_CLASIFICACION = "TC";
        }
        public struct CodigoCarpetaTipoSol
        {
            public const string SOL_CONTA = "CON";

        } 
        
        public struct MailBodies
        {
            public const string EXTERIOR_A_LIMA = @"           ";
            public const string  LIMA_A_EXTERIOR= @" ";
            public const string CONTABILIDAD_A_FINANZAS = @"";
            public const string EXTERIOR_A_LIMA_SUBSANADO = @"";



        }
        public struct MailSubjects
        {
            public const string CONTABILIDAD_DEVOLUCION = "DEVOLUCIÓN";
            public const string CONTABILIDAD_PRESUPUESTO = "PRESUPUESTO";
            public const string CONTABLIDAD_RENDICION_CUENTAS = "RENDICIÓN DE CUENTAS";
        }
        public struct MailLinks
        {
            public const string LINK_INTERNET_SOL = @"Gestion/solicitudes"; /*CORRESPONDE AL LINK DE LA CentroCosto*/
           
            public const string LINK_INTERNET_SOL_CONT_PRE = "gestion/contabilidad/presupuesto/{0}";
            public const string LINK_INTERNET_SOL_CONT_REN= "gestion/contabilidad/rendicion/{0}";
            public const string LINK_INTERNET_SOL_CONT_DEV = "gestion/contabilidad/devolucion/{0}";

        }

        public struct OrigenLogin
        {
            public const string EXTERIOR = "CentroCostoS";
            public const string BACKOFFICE = "BACKOFFICE";
        }
        public struct ResultadoLogin
        {
            public const string CORRECTO = "OK";
            public const string ERROR = "ERROR";
        }
        public struct AccionLogin
        {
            public const string LOGIN = "LOGIN";
            public const string LOGOUT = "LOGOUT";
        }

    }
}